all : flash

TARGET:=usbfs_cdc_tty
TARGET_MCU:=CH570 # currently only tested on ch570, ch582 and ch59x
TARGET_MCU_PACKAGE:=CH570D

include ../../../ch32fun/ch32fun.mk

flash : cv_flash
clean : cv_clean

